#!/bin/sh
image_name="vscode-server-$(head /dev/urandom | tr -dc 'a-z0-9' | fold -w 8 | head -n 1)"

docker build --build-arg ADDITIONAL_PACKAGES="$2" . -t $image_name -f src/docker/utils/dockerfile

# Start from port 8080
port=8080

# Function to check if a port is in use
is_port_in_use() {
    netstat -ltn | grep -q ":$1"
}

echo $1

# Find an available port
while is_port_in_use $port; do
    port=$((port+1))
done

echo "Launching on port $port and mounting $1"

# Run the Docker container with the available port
docker run -p $port:8080 -v "$1:/home/coder" --privileged -d $image_name